=== CostaHiripis/Data-Pocessing-Final-Assignment-REST-API/XmlAndJsonWithSchemas/Air-quality/air-quality.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

<!-- definition of simple elements -->
<xs:element name="country-name" type="xs:string"/>
<xs:element name="polutant" type="xs:string"/>
<xs:element name="variable" type="xs:string"/>
<xs:element name="year" type="xs:gYear"/>
<xs:element name="unit" type="xs:string"/>
<xs:element name="value" type="xs:float"/>

<!-- definition of complex elements -->
<xs:element name="country">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="country-name"/>
            <xs:element ref="polutant"/>
            <xs:element ref="variable"/>
            <xs:element ref="year"/>
            <xs:element ref="unit"/>
            <xs:element ref="value"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="air-quality-per-country">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="country" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== CostaHiripis/Data-Pocessing-Final-Assignment-REST-API/XmlAndJsonWithSchemas/Air-quality/air-quality.xml
<?xml version="1.0" encoding="UTF-8"?>
<air-quality-per-country xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="air-quality.xsd">

    <country>
        <country-name>Australia</country-name>
        <polutant>Sulphur Dioxide</polutant>
        <variable>Total man-made emissions</variable>
        <year>1990</year>
        <unit>Tonnes</unit>
        <value>1585.754</value>
    </country>
    
</air-quality-per-country>
